using System.Data;
using Microsoft.Data.SqlClient;
using CountriesProject.DAL.Models;

namespace CountriesProject.DAL
{
    public class QuizDAL : DBServices
    {
        public QuizDAL(IConfiguration config) : base(config) { }

        public List<Quiz> GetAll()
        {
            List<Quiz> list = new List<Quiz>();
            try
            {
                using (SqlConnection con = GetDBSConnection())
                {
                    SqlCommand cmd = new SqlCommand("sp_Quizzes_FP_RM_GetAll", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    con.Open();
                    SqlDataReader reader = cmd.ExecuteReader();
                    while (reader.Read())
                    {
                        list.Add(new Quiz
                        {
                            QuizId = (int)reader["QuizId"],
                            Title = reader["Title"].ToString(),
                            Description = reader["Description"] as string,
                            TimeLimitSeconds = (int)reader["TimeLimitSeconds"],
                            QuestionCount = (int)reader["QuestionCount"]
                        });
                    }
                }
                return list;
            }
            catch (Exception ex)
            {
                throw new Exception("Was not able to fetch data from the database.", ex);
            }

        }

        public Quiz GetById(int quizId)
        {
            Quiz quiz = null;
            try
            {
                using (SqlConnection con = GetDBSConnection())
                {
                    SqlCommand cmd = new SqlCommand("sp_Quizzes_FP_RM_GetById", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@QuizId", quizId);
                    con.Open();
                    SqlDataReader reader = cmd.ExecuteReader();
                    if (reader.Read())
                    {
                        quiz = new Quiz
                        {
                            QuizId = (int)reader["QuizId"],
                            Title = reader["Title"].ToString(),
                            Description = reader["Description"] as string,
                            TimeLimitSeconds = (int)reader["TimeLimitSeconds"],
                            QuestionCount = (int)reader["QuestionCount"]
                        };
                    }
                }
                return quiz;
            }
            catch (Exception ex)
            {
                throw new Exception("Was not able to fetch data from the database.", ex);
            }

        }

        public List<QuizQuestion> GetAllQuestions(int quizId)
        {
            List<QuizQuestion> list = new List<QuizQuestion>();
            try
            {
                using (SqlConnection con = GetDBSConnection())
                {
                    SqlCommand cmd = new SqlCommand("sp_QuizQuestions_FP_RM_GetForQuiz", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@QuizId", quizId);
                    con.Open();
                    SqlDataReader reader = cmd.ExecuteReader();
                    while (reader.Read())
                    {
                        list.Add(new QuizQuestion
                        {
                            QuestionId = (int)reader["QuestionId"],
                            QuizId = (int)reader["QuizId"],
                            QuestionText = reader["QuestionText"].ToString(),
                            OptionA = reader["OptionA"].ToString(),
                            OptionB = reader["OptionB"].ToString(),
                            OptionC = reader["OptionC"].ToString(),
                            OptionD = reader["OptionD"].ToString(),
                            CorrectOption = reader["CorrectOption"].ToString()
                        });
                    }
                }
                return list;
            }
            catch (Exception ex)
            {
                throw new Exception("Was not able to fetch data from the database.", ex);
            }

        }

        //attempts are used for the quiz history tab. the date of the attempt is generated by hte sp command itself, not her.
        public void InsertQuizAttempt(int userId, int quizId, int score, int timeTakenSeconds)
        {
            try
            {
                using (SqlConnection con = GetDBSConnection())
                {
                    SqlCommand cmd = new SqlCommand("sp_QuizAttempts_FP_RM_Insert", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@UserId", userId);
                    cmd.Parameters.AddWithValue("@QuizId", quizId);
                    cmd.Parameters.AddWithValue("@Score", score);
                    cmd.Parameters.AddWithValue("@TimeTakenSeconds", timeTakenSeconds);
                    con.Open();
                    cmd.ExecuteNonQuery();
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Was not able to add data to the database.", ex);
            }

        }

        public List<QuizAttempt> GetAllAttempts(int userId)
        {
            List<QuizAttempt> list = new List<QuizAttempt>();
            try
            {
                using (SqlConnection con = GetDBSConnection())
                {
                    SqlCommand cmd = new SqlCommand("sp_QuizAttempts_FP_RM_GetForUser", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@UserId", userId);
                    con.Open();
                    SqlDataReader reader = cmd.ExecuteReader();
                    while (reader.Read())
                    {
                        list.Add(new QuizAttempt
                        {
                            AttemptId = (int)reader["AttemptId"],
                            QuizId = (int)reader["QuizId"],
                            QuizTitle = reader["QuizTitle"].ToString(),
                            Score = (int)reader["Score"],
                            TimeTakenSeconds = (int)reader["TimeTakenSeconds"],
                            CompletedAt = (DateTime)reader["CompletedAt"]
                        });
                    }
                }
                return list;
            }
            catch (Exception ex)
            {
                throw new Exception("Was not able to fetch data from the database.", ex);
            }
        }

        public List<LeaderboardEntry> GetLeaderboard(int quizId, int top = 10)
        {
            List<LeaderboardEntry> list = new List<LeaderboardEntry>();
            try
            {
                using (SqlConnection con = GetDBSConnection())
                {
                    SqlCommand cmd = new SqlCommand("sp_QuizAttempts_FP_RM_GetLeaderboard", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@QuizId", quizId);
                    cmd.Parameters.AddWithValue("@Top", top);
                    con.Open();
                    SqlDataReader reader = cmd.ExecuteReader();
                    while (reader.Read())
                    {
                        list.Add(new LeaderboardEntry
                        {
                            Username = reader["Username"].ToString(),
                            Score = (int)reader["Score"],
                            TimeTakenSeconds = (int)reader["TimeTakenSeconds"],
                            CompletedAt = (DateTime)reader["CompletedAt"]
                        });
                    }
                }
                return list;
            }
            catch (Exception ex)
            {
                throw new Exception("Was not able to fetch data from the database.", ex);
            }

        }
    }
}